### ISSUE TITLE
x64: Build failure with gcc.

### ISSUE THREAD

**Issue by orbea** [tj90241/cen64#41]
OS: `Slackware64-current`
`gcc-5.3.0_multilib-x86_64-3alien`

I am building cen64 like this.
```
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="-O2 -fPIC" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release ..
  make
  make install DESTDIR=$PKG
cd ..
```
The error.
Full log - http://pastebin.com/8XrySxm2
```
collect2: error: ld returned 1 exit status
CMakeFiles/cen64.dir/build.make:1761: recipe for target 'cen64' failed
make[2]: *** [cen64] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cen64.dir/all' failed
make[1]: *** [CMakeFiles/cen64.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mikeryan** [comment]
Key element of the build failure log:

```
<artificial>:(.text.unlikely.device_debug_spin.lto_priv.186+0x960): undefined reference to `cen64_context_save'
<artificial>:(.text.unlikely.device_debug_spin.lto_priv.186+0xcb3): undefined reference to `cen64_context_restore'
```

This is caused by 0d087a0.

Are you on x86 or x64?

**Comment by orbea** [comment]
Slackware64-current so x86_64.

**Comment by orbea** [comment]
Thanks, it builds now.
